# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def gen_section(apps, schema_editor):
    Event = apps.get_model('cal', 'Event')
    Section = apps.get_model('courses', 'Section')
    for event in Event.objects.all():
        if event.course is not None:
            course = event.course
            section = Section.objects.filter(course=course).first()
            event.section = section
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170129_2149'),
        ('cal', '0004_auto_20170130_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
        migrations.RunPython(gen_section, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='event',
            name='course',
        ),
    ]
