# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


def gen_event_types(apps, schema_editor):
    CLASS_TYPE = 1
    Event = apps.get_model('cal', 'Event')
    for event in Event.objects.all():
        if event.section is not None:
            event.event_type = CLASS_TYPE
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20170207_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(1, 'Class'), (2, 'Social'), (3, 'Exercise'), (4, 'Shower'), (5, 'Meal')], null=True),
        ),
        migrations.RunPython(gen_event_types, reverse_code=migrations.RunPython.noop),
    ]
