# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'cal', '0011_auto_20170307_1033'), (b'cal', '0012_auto_20170307_1034')]

    dependencies = [
        ('cal', '0010_auto_20170307_0759_squashed_0012_auto_20170307_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartschedulingprefs',
            name='candidate_exercise_shower_delta',
            field=models.DurationField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='smartschedulingprefs',
            name='candidate_exercise_shower_duration',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
