# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_smartschedulingprefs_bed_shower_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartschedulingprefs',
            name='bed_shower_duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
    ]
