# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_smartschedulingprefs_bed_shower_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartschedulingprefs',
            old_name='bed_shower_time',
            new_name='bed_shower_start_time',
        ),
        migrations.RemoveField(
            model_name='smartschedulingprefs',
            name='bed_shower_duration',
        ),
        migrations.AddField(
            model_name='smartschedulingprefs',
            name='bed_shower_end_time',
            field=models.TimeField(default=datetime.time(22, 30)),
        ),
    ]
