# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170126_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructors',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='term_quarter',
            field=models.IntegerField(choices=[(0, b'Autumn'), (1, b'Winter'), (2, b'Spring'), (3, b'Summer')]),
        ),
    ]
