# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170127_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
