# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170127_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
