# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:37
from __future__ import unicode_literals

import courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170127_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=courses.models.DaysOfWeekField(),
        ),
    ]
