# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170127_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('subject', 'code')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('term_year', 'term_quarter')},
        ),
        migrations.AlterField(
            model_name='section',
            name='term_quarter',
            field=models.IntegerField(choices=[(0, b'Autumn'), (1, b'Winter'), (2, b'Spring'), (3, b'Summer')], verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='section',
            name='term_year',
            field=models.IntegerField(verbose_name='Academic year'),
        ),
    ]
